### PR TITLE
Feature/enemy files

### PR DESCRIPTION
**Pull request by rufio72**
This "Draft pull request" contains the schema with which I intend to separate enemy files. For now it's only relative to the crusher, if it's okay with you, I'll replicate this pattern on all the others. I am not a lua programmer, so if you have any suggestions or corrections, they are welcome. 
Bye!

### CODE REVIEW

**Comment by Jigoku** [comment]
Yep, something like this i did plan a long time ago, but never got round to doing it, and the enemies file has become a bit bloated ever since lol. That looks okay though :+1: 

One thing, i'm wondering what's with the choice here for `_G`?
```lua
_G[name].worldInsert(x,y,movespeed,movedist,dir,name)
```

**Comment by rufio72** [comment]
I needed to access to the crusher.worldInsert function in a dynamic way. In my idea every enemy file will have an enemyName.worldInsert function, I do not want to use the construction:

`if(name=="crusher") then crusher.worldInsert( etc, etc,) end`

In the function enemies:add I want to write only one line that will be:

`_G[varEnemyName].worldInsert( etc, etc,)`

Searching the internet I found that **_G** is used to access global variables so I used it.  I don't know if in Lua there is a better way, at the moment I know little about it.

**Comment by Jigoku** [comment]
> I needed to access to the crusher.worldInsert function in a dynamic way. In my idea every enemy file will have an enemyName.worldInsert function, I do not want to use the construction:
> if(name=="crusher") then crusher.worldInsert( etc, etc,) end
> In the function enemies:add I want to write only one line that will be:
> _G[enemyName].worldInsert( etc, etc,)
> Searching the internet I found that _G is used to access global variables so I used it. I don't know if in Lua there is a better way, at the moment I know little about it.

Oh i see now, I was just reading the Lua docs about `_G` as i'm not familiar with that built-in until now.
If it works there, go ahead with it.

> I don't know if in Lua there is a better way, at the moment I know little about it.

I'm no expert at Lua either :smile:

**Comment by rufio72** [comment]
Hi I have a little problem on some map files. 
Inside I find references to a "floater" enemy
Example: I find this in file 1_act2.lua, line 97: 
```
enemies:add(3110,-3100,100,400,1,"floater")
enemies:add(650,-3300,-100,418,0,"floater")
```
But I can't find any reference on the enemies.lua file.
Now I believe that floater is an old enemy that is no longer in the enemies.lua file, but has remained on the map files.
Tell me if I can delete its reference from the map file or if it should be kept. 
(or if i'm wrong)
Thank you
bye

**Comment by Jigoku** [comment]
> Inside I find references to a "floater" enemy

Yeah the "floater" was renamed to "bee", i probably forgot to change them there.

**Comment by rufio72** [comment]
Dear Jigoku
Looks like this feature is finished. Now I'll take a day to do the test and then I'll send you the pull request. If you have time to play it, if you find errors or things that can be optimized/improved send me a message.
Bye

**Comment by Jigoku** [comment]
Instead of removing the floater enemy from the maps, they could be renamed to; `enemies:add(10920,-4140,100,400,0,"bee")` as they act the same other than the name change.

**Comment by rufio72** [comment]
Ok, I renamed the floater

**Comment by rufio72** [comment]
I played on map 1 and 2 and found no bugs. Same thing on the tutorial map in edit mode.

**Comment by Jigoku** [comment]
Yep, nice job. Works better like that, should be alot easier and quicker to add more enemy types now :+1:

**Pull request merged**
